import os
import re

RAW_DATA_DIR = "data/raw"
PROCESSED_DATA_DIR = "data/processed"

os.makedirs(PROCESSED_DATA_DIR, exist_ok=True) # Ensure output directory exists

def clean_text(text):
    '''
    Function to clean anatomy textbook pdfs by removing headers, footers, figure labels, page artifacts, and weird whitespace
    REGEX GENERATED BY CHATGPT on 10/24/2025
    '''
    text = re.sub(r'^\s*\d+\s*$', '', text, flags=re.MULTILINE) # Remove page numbers or numeric-only lines
    text = re.sub(r'CHAPTER\s+\d+\s+•\s+[A-Za-z\s]+?\d*', '', text, flags=re.IGNORECASE) # Remove headers and footers
    text = re.sub(r'M\d+_.*?indd.*', '', text) # Remove filenames
    text = re.sub(r'\d{1,2}/\d{1,2}/\d{2,4}\s+\d{1,2}:\d{2}\s*(?:AM|PM)?', '', text) # Remove date and time stamps
    text = re.sub(r'(FIGURE|TABLE)\s+\d+[–-]?\d*\s*■', '', text, flags=re.IGNORECASE) # Remove figure and table references
    text = re.sub(r'\b[A-Z](?:\s[A-Z]){2,}\b', '', text) # Remove all caps titles
    text = re.sub(r'[•■]', '', text) # Remove bullet dots and weird unicode
    
    # Collapse multiple newlines or spaces
    text = re.sub(r'\n+', '\n', text)
    text = re.sub(r'\s+', ' ', text)
    
    return text.strip()

def main():
    for filename in os.listdir(RAW_DATA_DIR): # Process all text files in the raw data directory
        if filename.lower().endswith(".txt"):
            file_path = os.path.join(RAW_DATA_DIR, filename) # Path to the file
            with open(file_path, "r") as f:
                raw_text = f.read()
            cleaned_text = clean_text(raw_text) # Clean the text
            out_name = os.path.splitext(filename)[0] + ".txt"
            out_path = os.path.join(PROCESSED_DATA_DIR, out_name)

            with open(out_path, "w") as f:
                f.write(cleaned_text)
            print(f"Processed {filename}")

if __name__ == "__main__":
    main()
